### ISSUE TITLE
Why we receive so many travis ci failure about RocketMQ

### ISSUE THREAD

**Issue by vongosling** [repairnator/repairnator-experiments#1]
Build Update for Spirals-Team/librepair-experiments
-------------------------------------

Build: #6537
Status: Failed

Duration: 3 minutes and 38 seconds
Commit: 247602f (apache-rocketmq-287487904-20171013-115230_bugonly)
Author: Luc Esape
Message: Bug commit from the following repository apache/rocketmq
This bug commit is a reflect of source code from: http://github.com/apache/rocketmq/commit/ce06e292a3a57b518e571f2747ddb66b566d3d7e.

View the changeset: https://github.com/Spirals-Team/librepair-experiments/commit/247602f24de8

View the full build log and details: https://travis-ci.org/Spirals-Team/librepair-experiments/builds/287494088?utm_source=email&utm_medium=notification

Hello, Could you tell me how do you use RocketMQ and for what purpose :-)

**Comment by surli** [comment]
Hi @vongosling 

I'm sorry for the notifications: I'm working on a research project aiming in reproducing PR failing builds and analyzing them. I'm pushing the reproduced failure and activated Travis on this repository: I did not think that some projects would receive notification emails from the failing builds we create...

I deactivated for now Travis for my repository so you should not receive notifications anymore. I will try to automatically remove email adresses from .travis.yml before pushing and activate again Travis after that: don't hesitate to come back if you receive some more emails!
